server:
  port : 12010
        
spring:
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     jdbcUrl: jdbc:postgresql://10.138.0.2:5432/quecs
     username: quecs
     password: mysecretpassword